Debug 0
GenericExecuteSynth \
"printf %s \'$DATA\' | __PIPER__ -m __VOICES__/\'$VOICE\'.onnx --output-raw 2>/dev/null | aplay -q -r 22050 -f S16_LE -t raw -"
GenericCmdDependency "__PIPER__"
GenericPunctNone ""
GenericPunctSome ""
GenericPunctMost ""
GenericPunctAll ""
GenericRateAdd 0
GenericPitchAdd 0
GenericVolumeAdd 0
AddVoice	"en"	"FEMALE1"	"en_US-hfc_female-medium"
AddVoice	"en"	"FEMALE2"	"en_US-amy-medium"
DefaultVoice	"en_US-hfc_female-medium"
